### ISSUE TITLE
Add link to YouTube  and LinkedIn at end of the landing page

### ISSUE THREAD

**Issue by SvenSchran** [ASRG/asrg.io#255]
Besides the Links to Twitter, LinkedIn etc. a link to the YouTube channel should be added.

**Comment by heldyboy** [comment]
https://html5up.net/spectral

**Comment by alanamircruz** [comment]
@peterbogdan brother I ran all the services, plus the envs and requirements and I got this exception:

```
ERROR: for asrg-postgres  Cannot create container for service asrg-db: status code not OK but 500:  ╔   ˙˙˙˙╔       
                                                                                                                    ╗   FDocker.Core, Version=3.3.0.62907, Culture
=neutral, PublicKeyToken=null║╔   ?Docker.Core.DockerException
                                                                       ClassNameMessage╝DataInnerExceptionHelpURLStackTraceStringRemoteStackTraceStringRemoteS
WatsonBuckets╔╔╚╚╔╔╔ ╔ ╔System.Collections.IDictionarySystem.Excepti╗╗   ═╚   ?Docker.Core.DockerException═╝   Filesharing has been cancelled


═║   Ś   at Docker.ApiServices.Mounting.FileSharing.<DoShareAsync>d__7.MoveNext() in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.ApiService
s\Mounting\FileSharing.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.Mounting.FileSharing.<ShareAsync>d__5.MoveNext() in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.ApiServices\Mountin
g\FileSharing.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.HttpApi.Controllers.FilesharingController.<ShareDirectory>d__2.MoveNext() in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.HttpAp
i\Controllers\FilesharingController.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
    ══   Ł╔8
MoveNext
Docker.ApiServices, Version=3.3.0.62907, Culture=neutral, PublicKeyToken=null
Docker.ApiServices.Mounting.FileSharing+<DoShareAsync>d__7
Void MoveNext() €═   Docker.ApiServices

ERROR: for asrg-db  Cannot create container for service asrg-db: status code not OK but 500:  ╔   ˙˙˙˙╔       
                                                                                                              ╗   FDocker.Core, Version=3.3.0.62907, Culture=neutr
al, PublicKeyToken=null║╔   ?Docker.Core.DockerException
                                                               ClassNameMessage╝DataInnerExceptionHelpURLStackTraceStringRemoteStackTraceStringRemoteStackInde
WatsonBuckets╔╔╚╚╔╔╔ ╔ ╔System.Collections.IDictionarySystem.Excepti╗╗   ═╚   ?Docker.Core.DockerException═╝   Filesharing has been cancelled


═║   Ś   at Docker.ApiServices.Mounting.FileSharing.<DoShareAsync>d__7.MoveNext() in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.ApiService
s\Mounting\FileSharing.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.Mounting.FileSharing.<ShareAsync>d__5.MoveNext() in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.ApiServices\Mountin
g\FileSharing.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.HttpApi.Controllers.FilesharingController.<ShareDirectory>d__2.MoveNext() in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.HttpAp
i\Controllers\FilesharingController.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
    ══   Ł╔8
MoveNext
Docker.ApiServices, Version=3.3.0.62907, Culture=neutral, PublicKeyToken=null
Docker.ApiServices.Mounting.FileSharing+<DoShareAsync>d__7
Void MoveNext() €═   Docker.ApiServices
ERROR: Encountered errors while bringing up the project.
```


Whenever you have a chance brother, please support.

**Comment by SvenSchran** [comment]
Link to YouTube is still missing in the Footer (see added picture).

![grafik](https://user-images.githubusercontent.com/75367305/123559453-625c0580-d79c-11eb-8b3f-50dd5385e7c0.png)

**Comment by SvenSchran** [comment]
see comment given 1 minute ago

**Comment by alanamircruz** [comment]
I am checking towards the latest updates on the website.
